services:
  app1:
    image: first-laba:1.0
    container_name: app1
    expose:
      - "6080"
    volumes:
      - .:/server

  app2:
    image: first-laba:1.0
    container_name: app2
    expose:
      - "6080"
    volumes:
      - .:/server

  app3:
    image: first-laba:1.0
    container_name: app3
    expose:
      - "6080"
    volumes:
      - .:/server

  app4:
    image: first-laba:1.0
    container_name: app4
    expose:
      - "6080"
    volumes:
      - .:/server

  nginx:
    image: first-laba-nginx:1.0
    container_name: nginx
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - app1
      - app2
      - app3
      - app4