services:
  app1:
    build: ./app
    container_name: app1
    expose:
      - 8080
    volumes:
      - .:/app

  app2:
    build: ./app
    container_name: app2
    expose:
      - 8080
    volumes:
      - .:/app

  app3:
    build: ./app
    container_name: app3
    expose:
      - 8080
    volumes:
      - .:/app

  app4:
    build: ./app
    container_name: app4
    expose:
      - 8080
    volumes:
      - .:/app

  nginx:
    build: ./LB
    container_name: nginx
    ports:
      - 6080:80
    depends_on:
      - app1
      - app2
      - app3
      - app4